site_name: MIT - The Missing Semester of Your CS Education
repo_url: https://github.com/hantang/wayback-missing-semester
site_url: https://hantang.github.io/wayback-missing-semester/

theme:
  name: material
  favicon: assets/favicon.ico
  icon:
      logo: fontawesome/solid/terminal
  font:
    text: Open Sans, Helvetica Neue, Roboto, sans-serif, serif
    code: Fira Mono, Fira Code, Roboto Mono, monospace
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    - content.code.copy

markdown_extensions:
  - abbr
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      line_spans: __span
      linenums_style: pymdownx-inline
      linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search

# extra:
#   alternate:
#     - name: English
#       link: /en/ 
#       lang: en
#     - name: 简体中文
#       link: /zh/
#       lang: zh

plugins:
  - search
  - i18n:
      docs_structure: folder # suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 简体中文
          build: true
          site_name: 计算机教育中缺失的一课
          nav_translations:
            Home: 课程首页
            Lectures: 讲座列表
            Archive: 归档课程
            About: 关于本课程
            Solution: 习题解答
            Introduction: 课程简介

nav:
  - Home: index.md
  - Lectures:
    - Introduction: 2020/index.md
    - 2020/course-shell.md
    - 2020/shell-tools.md
    - 2020/editors.md
    - 2020/data-wrangling.md
    - 2020/command-line.md
    - 2020/version-control.md
    - 2020/debugging-profiling.md 
    - 2020/metaprogramming.md
    - 2020/security.md
    - 2020/potpourri.md
    - 2020/qa.md
  - Solution:
    - 2020/solutions/course-shell-solution.md
    - 2020/solutions/shell-tools-solution.md
    - 2020/solutions/editors-solution.md
    - 2020/solutions/data-wrangling-solution.md
    - 2020/solutions/command-line-solution.md
    - 2020/solutions/version-control-solution.md
    - 2020/solutions/debugging-profiling-solution.md 
    - 2020/solutions/metaprogramming-solution.md
    - 2020/solutions/security-solution.md
  - Archive:
    - 2019 Lectures: 2019/index.md
  - About: about.md
  - License: license.md
